sudo: false
language: go
go:
 - 1.5
 - release
 - tip

before_install:
 - go get github.com/axw/gocov/gocov
 - go get github.com/mattn/goveralls
 - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi


script:
 - $HOME/gopath/bin/goveralls -repotoken $COVERALLS_TOKEN

env:
  global:
    secure: "jqe3HU9kxygPPnSh/V7ffIra/qUTgYvLsJnCR+MChNJYSxpJPs0uK2+uK6dnQzKel2LfuyABsLzlNpNJE0pijR1d88bzQ9VxM4BGJ+Qv1AyG2CeM7a08eeZVlU77LvBOHjaFDIruoJMFwsv7DzudzPZzc/FAtMkO/4RbIs+VGAA="
